services:
  adguardhome:
    container_name: adguardhome
    image: adguard/adguardhome
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
      - "443:443/tcp"
      - "443:443/udp"
      - "3000:3000/tcp"
      - "853:853/tcp"
    volumes:
      - ./data/work:/opt/adguardhome/work
      - ./data/conf:/opt/adguardhome/conf
    networks:
      adguard_net:
        ipv4_address: ${ADGUARDHOME_IPV4_ADDRESS}
    labels:
      - traefik.enable=true
      - traefik.http.routers.adguardhome.rule=Host(`${ADGUARDHOME_HOSTNAME}`)
      - traefik.http.routers.adguardhome.entrypoints=websecure
      - traefik.http.routers.adguardhome.tls=true
      - traefik.http.routers.adguardhome.tls.certresolver=cloudflare
      - traefik.http.services.adguardhome.loadbalancer.server.port=80
      - docker-volume-backup.stop-during-backup=true

networks:
  adguard_net:
    driver: macvlan
    driver_opts:
      parent: ${ADGUARDHOME_MACVLAN_NETWORK_CARD}
    ipam:
      config:
        - subnet: ${ADGUARDHOME_MACVLAN_SUBNET}
          gateway: ${ADGUARDHOME_MACVLAN_GATEWAY}
          ip_range: ${ADGUARDHOME_IPV4_ADDRESS}/32
